Review
MaksimShershnev/blog-customizer pull request #1
Opened 2024-04-05 07:17 UTC by MaksimShershnev

Реализована работа сайдбара с параметрами

2024-04-05 13:17 UTC, olgalatkina requested changes
Добрый день!

**У вас получилась отличная работа:**
- Реализован весь функционал.
- Состояния страницы и сайдбара разделены.
- Сайдбар закрывается по клику вне сайдбара.
-  Для условного добавления стилей используется библиотека `clsx`.
- Типизированы все пропсы и события.

**Но есть несколько моментов, которые надо поправить:**
- [ ] Проект не соответствует макету: у заголовка формы появилась тень и он меняет стиль шрифта вместе со страницей.
- [ ] Событие `submit` должно быть на форме, а не на кнопке.
- [ ] Для дефолтных состояний статьи и формы не используется нулевые индексы.

**Правки можно лучше остаются на ваше усмотрение:**
- [ ]  Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx` (см. компоненты `Article` и `App`).

Успешного рефакторинга!

2024-04-05 13:17 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.stories.tsx
> +			<ArrowButton isOpen={isOpen} setIsOpen={setIsOpen} />
_надо исправить:_
Не стоит использовать хуки реакта внутри сторибуковского компонента.

здесь достаточно написать так:
```
<ArrowButton isOpen={true} setIsOpen={() => console.log('')} />
```

2024-04-05 13:17 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	setIsOpen: (isOpen: boolean) => void;
_можно лучше:_
`setIsOpen: OnClick;` 
следующим шагом избавляемся от `type OnClick` и получаем:

```
type ArrowButtonProps = {
	isOpen: boolean;
	setIsOpen: () => void;
};
```

2024-04-05 13:17 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	const handleClick: OnClick = () => {
_можно лучше:_
Эта обёртка над функцией тоже не нужна.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			onClick={handleClick}
_можно лучше:_
Теперь можем сразу из пропсов закинуть обработчик в `onClick`: 
```
onClick={setIsOpen}
```
Останется лишь поправить то, что передаём в компонент. Комментарий будет по месту в коде.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 50px;
_отлично:_
Оптимальное решение здесь и в этом же css-классе ниже.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +			<ArrowButton isOpen={isOpen} setIsOpen={setIsOpen} />
_можно лучше:_
Тут завершаем рефакторинг, начатые в компонренте `ArrowButton`:
```
<ArrowButton isOpen={isOpen} setIsOpen={() => setIsOpen(!isOpen)} />
```

2024-04-05 13:17 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, isOpen && styles.container_open)}>
_отлично:_
Отлично, что используете библиотеку `clsx`

2024-04-05 13:17 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
_можно лучше:_
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/text/index.module.scss
> +.text-shadow {
_надо исправить:_
Не соответствует макету.
Не уверена, что дизайнер одобрил бы такое творчество - заголовок с тенью выбивается из общей стилистики макета. Изменение стиля заголовка тоже вряд ли было задумано.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/select/hooks/useOutsideClickClose.ts
> +		window.addEventListener('mousedown', handleClick);
_отлично:_
Отлично, что починили хук.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +						<Button title='Применить' type='submit' onClick={handleFormSubmit} />
_надо исправить:_
Обработчик события `submit` должен навешиваться на форму, а не на клик по кнопке. 
В браузере у формы событие `submit` так же срабатывает при нажатии на Enter. 
Подробнее тут: https://doka.guide/js/event-submit/#na-praktike

2024-04-05 13:17 UTC, olgalatkina commented on src/components/button/Button.tsx
> +	onClick?: (e: SyntheticEvent<HTMLButtonElement>) => void;
_можно лучше:_
Нет необходимости менять типизацию. Событие `submit` навешивам на форму, а не на кнопку.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formState = {
_можно лучше:_
Если объект нужен только при вызове функции, то нужно объявить его внутри функции, а не в теле компонента.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		setCurrentFontFamily(fontFamilyOptions[0]);
_надо исправить:_
Настройки статьи по умолчанию описаны в объекте `defaultArticleState`  в файле `constants/articleProps.ts` стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.
Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств. То что настройки по умолчанию имеют именно нулевой индекс можно считать просто совпадением и это может измениться в любой момент.

2024-04-05 13:17 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formRef = useRef<HTMLDivElement>(null);
_надо исправить:_
Поскольку инициализируем реф значением `null`, то тип будет:
```
const formRef = useRef<HTMLDivElement | null>(null);
```

2024-04-05 13:24 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleFormSubmit = (e: SyntheticEvent<HTMLButtonElement>) => {
_можно лучше:_
В React для типизации события  формы используется тип `React.FormEvent<HTMLFormElement>`

2024-04-06 15:36 UTC, MaksimShershnev commented on src/components/arrow-button/ArrowButton.stories.tsx
> +			<ArrowButton isOpen={isOpen} setIsOpen={setIsOpen} />
Делал по аналогии с RadioGroup.stories, там использовался хук. Убрал

2024-04-06 16:05 UTC, MaksimShershnev commented on src/components/arrow-button/ArrowButton.tsx
> +	setIsOpen: (isOpen: boolean) => void;
Исправлено

2024-04-06 16:05 UTC, MaksimShershnev commented on src/components/arrow-button/ArrowButton.tsx
> +	const handleClick: OnClick = () => {
Обертка удалена

2024-04-06 16:06 UTC, MaksimShershnev commented on src/components/arrow-button/ArrowButton.tsx
> +			onClick={handleClick}
Исправлено

2024-04-06 16:06 UTC, MaksimShershnev commented on src/components/article-params-form/ArticleParamsForm.tsx
> +						<Button title='Применить' type='submit' onClick={handleFormSubmit} />
Исправлено

2024-04-06 16:07 UTC, MaksimShershnev commented on src/components/button/Button.tsx
> +	onClick?: (e: SyntheticEvent<HTMLButtonElement>) => void;
Исправлено

2024-04-06 16:07 UTC, MaksimShershnev commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formState = {
Исправлено

2024-04-06 16:08 UTC, MaksimShershnev commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		setCurrentFontFamily(fontFamilyOptions[0]);
Исправлено. Данные теперь берутся из объекта defaultArticleState

2024-04-06 16:08 UTC, MaksimShershnev commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formRef = useRef<HTMLDivElement>(null);
Исправлено

2024-04-06 16:08 UTC, MaksimShershnev commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleFormSubmit = (e: SyntheticEvent<HTMLButtonElement>) => {
Спасибо! исправлено

2024-04-07 06:12 UTC, olgalatkina approved these changes
Отличная работа! Проект принимается🎉

2024-04-08 09:16 UTC, merged